import Head from "next/head";
import React from "react";
import { getPostList } from "../lib/post";
import Header from "../components/Header";
import Link from "next/link";
import DateString from "../components/DateString";

export default function Home({ postList }) {
  return (
    <div className="w-full h-full">
      <Head>
        <title>Next.js Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="w-full py-8 px-5 lg:px-36 flex flex-col gap-8 items-center">
        <div className="w-full">
          <h1 className="font-bold text-3xl lg:text-6xl text-center lg:text-left">
            Next.js Blog
          </h1>
        </div>

        <div className="flex flex-col gap-4 w-full items-center">
          {/* featured blog post */}
          <Link
            href={`/posts/read/${postList[0].id}`}
            className="flex flex-col lg:flex-row w-full gap-5 justify-start lg:justify-between transition-colors hover:bg-slate-300 p-5 rounded-xl"
          >
            <div className="w-full lg:w-1/2 h-fit rounded-xl overflow-hidden">
              <img src={postList[0].img} className="w-full" alt="cat" />
            </div>
            <div className="w-full lg:w-1/2 flex flex-col gap-2 lg:gap-4">
              <p className="text-sm lg:text-lg text-gray-600">
                <DateString timestamp={postList[0].date} />
              </p>
              <h2 className="text-2xl lg:text-4xl font-bold">
                {postList[0].title}
              </h2>
              <h2 className="text-md lg:text-lg text-justify">
                {postList[0].body.substr(0, 200)}...
              </h2>
            </div>
          </Link>

          {/* other blog post */}
          <div className="grid grid-cols-2 lg:grid-cols-3 gap-0 lg:gap-5">
            {postList.slice(1, 7).map((item, index) => {
              return (
                <Link
                  key={index}
                  href={`/posts/read/${item.id}`}
                  className="flex flex-col w-full gap-5 justify-start transition-colors hover:bg-slate-300 p-5 rounded-xl"
                >
                  <div className="w-full h-fit rounded-xl overflow-hidden">
                    <img src={item.img} className="w-full" alt="cat" />
                  </div>
                  <div className="w-full flex flex-col justify-start gap-2">
                    <p className="text-xs lg:text-sm text-gray-600">
                      <DateString timestamp={item.date} />
                    </p>
                    <h2 className="text-lg lg:text-xl font-bold">
                      {item.title}
                    </h2>
                    <h2 className="text-sm lg:text-md text-justify">
                      {item.body.substr(0, 200)}...
                    </h2>
                  </div>
                </Link>
              );
            })}
          </div>

          <Link
            href="/posts/1"
            className="w-fit px-6 py-2 text-center text-xl text-biru-tua hover:text-biru-muda hover:underline underline-offset-4 transition-colors rounded-xl group"
          >
            See more &nbsp;{" "}
            <i className="fa-solid fa-right-long text-biru-tua group-hover:text-biru-muda group-hover:underline transition-colors"></i>
          </Link>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const { data: postList } = await getPostList(1, 7);
  return {
    props: { postList },
  };
}
